server:
  shutdown: graceful
#  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/next_class?serverTimezone=Asia/Seoul
    username: dev_user
    password: 1q2w3e4r!@

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

