server:
  shutdown: graceful
#  port: 8080

spring:
  datasource:
    url: ENC(bbwMSBT+KpAPmpE30IjXoLj1N2EobGXZaNr/pgUQd0syGw+/Pse47Ez5lQjEwX6ajtjrkJUnFgnbHAv720/Jm0ygECQl4k7wF/HX3XtHxw9HpW92qSML71j9TcVu9vH8pIc/QZ0SyVc4zSpxjTY3AQ==)
    username: ENC(mNSqvIBy/cEVdG5Hm6zOeb4YC0RPkTfy8XtQ91Hq2udwgvCXJ8UJQswf4bcYZrjT)
    password: ENC(c/FNrmem1msjiSZ3qZbNIuR3s8u/XoGwY5mtk8y7qrl8wdhLcSMnDQyfrPTUs1E4)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
    hibernate:
        ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
jasypt:
  encryptor:
    bean: jasyptEncryptor

