server:
  shutdown: graceful
#  port: 8080

spring:
  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: none
jasypt:
  encryptor:
    bean: jasyptEncryptor

jwt:
  expiration_time: 863400000
  secret: blackcow
